// Generated by CoffeeScript 1.3.3
(function() {
  var amf, requestPacket, responsePacket, utils;

  amf = require('./node-amf/amf');

  utils = require('./node-amf/utils');

  requestPacket = amf.packet(body);

  responsePacket = amf.packet();

  responsePacket.version = amf.AMF3;

}).call(this);
