// Generated by CoffeeScript 1.3.3
(function() {
  var listenHost, listenPort, methods, server, timeout;

  listenPort = 8088;

  listenHost = 'localhost';

  timeout = 5000;

  methods = require('./amf-methods');

  server = require('./node-amf/http-server');

  (function() {
    console.dir(methods);
    return server.start(listenPort, listenHost, methods, timeout);
  })();

}).call(this);
